[versions]
agp = "8.5.2"
kotlin = "1.9.24"

compileSdk = "34"
minSdk = "26"
targetSdk = "34"

compose-bom = "2024.06.00"
activity-compose = "1.9.0"
core-ktx = "1.13.1"

junit = "4.13.2"
androidx-junit = "1.1.5"
espresso = "3.5.1"

[libraries]

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
